update

diff --git a/sources/functions/rutorrent b/sources/functions/rutorrent
--- a/sources/functions/rutorrent
+++ b/sources/functions/rutorrent
@@ -8,7 +8,7 @@ function rutorrent_install() {
         echo_progress_start "Cloning ruTorrent"
         # Get current stable ruTorrent version
         release=$(git ls-remote --tags --refs https://github.com/novik/ruTorrent.git | awk '{sub("refs/tags/", ""); print $2 }' | grep -v beta | sort -Vr | head -n1)
-        git clone --recurse-submodules --depth 1 -b ${release} https://github.com/Novik/ruTorrent.git /srv/rutorrent >> "$log" 2>&1 || {
+        git clone --recurse-submodules --depth 1 -b ${release} https://github.com/Novik/ruTorrent.git /srv/rutorrent >>"$log" 2>&1 || {
             echo_error "Failed to clone ruTorrent"
             exit 1
         }
@@ -36,7 +36,7 @@ function rutorrent_install() {
     #fi
 
     if [[ ! -d /srv/rutorrent/plugins/filemanager ]]; then
-        git clone https://github.com/nelu/rutorrent-filemanager /srv/rutorrent/plugins/filemanager >> ${log} 2>&1 || { echo_error "git of autodl plugin to main plugins seems to have failed"; }
+        git clone https://github.com/nelu/rutorrent-filemanager /srv/rutorrent/plugins/filemanager >>${log} 2>&1 || { echo_error "git of autodl plugin to main plugins seems to have failed"; }
         rutorrent_fm_config
         #pinning filemanager should no longer be required
         #git -C /srv/rutorrent/plugins/filemanager checkout 234f5f20841ad3d1e3c095e6c6954a875fc8a6ea >> ${log} 2>&1
@@ -44,7 +44,7 @@ function rutorrent_install() {
 
     if [[ ! -d /srv/rutorrent/plugins/ratiocolor ]]; then
         cd /srv/rutorrent/plugins
-        svn co https://github.com/Gyran/rutorrent-ratiocolor.git/trunk ratiocolor >> "$log" 2>&1
+        svn co https://github.com/Gyran/rutorrent-ratiocolor.git/trunk ratiocolor >>"$log" 2>&1
         sed -i "s/changeWhat = \"cell-background\";/changeWhat = \"font\";/g" /srv/rutorrent/plugins/ratiocolor/init.js || { echo_error "git of autodl plugin to main plugins seems to have failed"; }
     fi
 
@@ -54,7 +54,7 @@ function rutorrent_install() {
         rutorrent_fix_quota
     fi
 
-    cat > /srv/rutorrent/conf/config.php << 'RUC'
+    cat >/srv/rutorrent/conf/config.php <<'RUC'
 <?php
 	// configuration parameters
 
@@ -147,7 +147,7 @@ function rutorrent_fm_config() {
     # Reconfigure file manager plugin for ARM64 support
     # rar is not supported on arm, so it needs to be dropped
     if [[ "$(_os_arch)" = "arm64" ]]; then
-        cat > /srv/rutorrent/plugins/filemanager/conf.php << 'RUFMC'
+        cat >/srv/rutorrent/plugins/filemanager/conf.php <<'RUFMC'
 <?php
 
     global $pathToExternals;
@@ -194,7 +194,7 @@ function rutorrent_nginx_config() {
     if [[ ! -f /etc/nginx/apps/rutorrent.conf ]]; then
         phpversion=$(php_service_version)
         sock="php${phpversion}-fpm"
-        cat > /etc/nginx/apps/rutorrent.conf << RUM
+        cat >/etc/nginx/apps/rutorrent.conf <<RUM
 location /rutorrent {
   auth_basic "What's the password?";
   auth_basic_user_file /etc/htpasswd;
@@ -211,7 +211,7 @@ RUM
     fi
 
     if [[ ! -f /etc/nginx/apps/rindex.conf ]]; then
-        cat > /etc/nginx/apps/rindex.conf << RIN
+        cat >/etc/nginx/apps/rindex.conf <<RIN
 location /rtorrent.downloads {
   alias /home/\$remote_user/torrents/rtorrent;
   include /etc/nginx/snippets/fancyindex.conf;
@@ -231,7 +231,7 @@ function rutorrent_user_config() {
     for user in "${users[@]}"; do
         if [[ ! -f /srv/rutorrent/conf/users/${user}/config.php ]]; then
             mkdir -p /srv/rutorrent/conf/users/${user}/
-            cat > /srv/rutorrent/conf/users/${user}/config.php << RUU
+            cat >/srv/rutorrent/conf/users/${user}/config.php <<RUU
 <?php
 \$topDirectory = '/home/${user}';
 \$scgi_port = 0;
@@ -243,7 +243,7 @@ RUU
         fi
 
         if [[ ! -f /etc/nginx/apps/${user}.scgi.conf ]]; then
-            cat > /etc/nginx/apps/${user}.scgi.conf << RUC
+            cat >/etc/nginx/apps/${user}.scgi.conf <<RUC
 location /${user} {
 include scgi_params;
 scgi_pass unix:/var/run/${user}/.rtorrent.sock;
@@ -256,7 +256,7 @@ RUC
 }
 
 function rutorrent_fix_quota() {
-    cat > /srv/rutorrent/plugins/diskspace/action.php << 'DSKSP'
+    cat >/srv/rutorrent/plugins/diskspace/action.php <<'DSKSP'
 <?php
 #################################################################################
 ##  [Quick Box - action.php modified for quota systems use]
